#version 450
#extension GL_GOOGLE_include_directive : enable
#define IS_AVAILABLE_BUFFER_GLOBAL_MUTABLES
#define IS_AVAILABLE_BUFFER_WORLD
#define IS_AVAILABLE_BUFFER_WORLD_COPY
#define IS_AVAILABLE_BUFFER_BLOCKS_TO_BE_INSERTED_OR_REMOVED
//#extension GL_EXT_debug_printf : enable

#include "descriptors_ambience.comp"
layout (local_size_x_id = GROUP_SIZE_CONST_ID) in;
#include "utils.comp"

void main() {
    uint gID = gl_GlobalInvocationID.x;
    uint blocks_to_be_inserted_or_removed_count = global_mutables.blocks_to_be_inserted_or_removed;
    if (gID < blocks_to_be_inserted_or_removed_count){
        const uint block_idx = blocks_to_be_inserted_or_removed[gID];
        set_block_id(block_idx,get_block_id_copy(block_idx));
    }
}